### PR TITLE
feat: video player integration

### PR DESCRIPTION
**Pull request by moskalakamil**
**Feature: Video Player Integration**

This PR implements a video player for the app.

### Changes:
- [x] Added sample public videos and corresponding thumbnails.
- [x] Added a thumbnail on the `main` and `details` screens.
- [x] Added a video player to the `player` screen.
- [x] Implemented custom controls for Android TV and Android-based OSes, including play/pause, seek, back functions.
- [x] Kept native controls for Apple TV.
- [x] Working web support

### Testing:
- Prebuild the app.
- Run `yarn install` in the root directory.
- Use `yarn android --devices` and select a TV device.
- Install Pods
- Use `yarn ios`.

I've even tested it on Fire TV! :)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution under the terms of your choice.

### CODE REVIEW

**Comment by moskalakamil** [comment]
Hey @giolaq, I've set up a draft PR to integrate the video player. Could you take a look when you have a chance and let me know what you think?

**Comment by giolaq** [comment]
Hi @moskalakamil ! This is great, I was actually thinking to add a proper video player screen. Feel free to add on this PR! :🔝

**Comment by moskalakamil** [comment]
Hey! @giolaq 👋

I've implemented the changes I described earlier - sorry it took a bit longer, but I got it done! :)) Additionally, I have a suggestion that could be an interesting addition to this project.

As maintainers of react-native-video, we’ve been working on some video examples, including support for DRM-protected content. We created a component where the user pastes a token generated by a form, and once it's added, everything works smoothly (you can find the example here: [DRMExample.tsx](https://github.com/TheWidlarzGroup/react-native-video/blob/master/examples/bare/src/DRMExample.tsx#L38C3-L42C60)).

We haven’t fully completed this yet, but we’re almost there. I was thinking it might be worth considering adding even one video with DRM support to your app. Applications like yours often leverage this kind of mechanism, so it could be a cool way to expand functionality and compatibility with more advanced playback scenarios.

Let me know what you think! 😊

**Comment by giolaq** [comment]
Thank you @moskalakamil ! It looks great, the only thing with this app we want to support even the web-based TVs. Any idea about how to support the video player also in this case?
Worse case scenario we can differentiate player.tsx for web and android/tvOS.

I totally like the idea to support DRM!

**Comment by moskalakamil** [comment]
I get it, I’ll come back with an answer tomorrow

**Comment by moskalakamil** [comment]
I need a little more time to fully sort this out; I'll get back to you asap

**Comment by moskalakamil** [comment]
Hi @giolaq, we are planning to add basic web support for react-native-video soon, and I'll keep you updated once it's live. In the meantime, we just finished implementing the DRM logic for our example today, so you can [check it out](https://github.com/TheWidlarzGroup/react-native-video/blob/master/examples/bare/src/DRMExample.tsx) to see how it looks in rnv repo

**Comment by giolaq** [comment]
Amazing thank you!

**Comment by moskalakamil** [comment]
Hi @giolaq, good news! Web support is working now as well

**Comment by giolaq** [comment]
Thank you @moskalakamil! Amazing work

**Review by giolaq — APPROVED** [review]

**Comment by moskalakamil** [comment]
Thank you 🙌

**Pull request merged**
